name: CI

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: debian:testing
      options: --privileged
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4
    - name: Run a multi-line script
      run: |
          apt-get update -qq
          apt-get install -yqq binfmt-support qemu-user-static podman mmdebstrap debuerreotype jq pigz
          cd examples
          mkdir my-debian-image-{{ matrix.arch }}
          ./debian.sh --arch={{ matrix.arch }} my-debian-image-{{ matrix.arch }} testing 2024-05-21T03:00:22Z
          ./oci-image.sh my-testing-{{ matrix.arch }}.tar my-debian-image-{{ matrix.arch }}/20240521/{{ matrix.arch }}/testing/
          ./oci-image.sh my-testing-slim-{{ matrix.arch }}.tar my-debian-image-{{ matrix.arch }}/20240521/{{ matrix.arch }}/testing/slim/

    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: examples/my-testing*tar
